name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "14 12 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
  
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: alwaysgreen
        run: |
          git config --local user.email "rui@celyi.com"
          git config --local user.name "rui1115"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.MY_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
